apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: ratings-test-abort
spec:
  destination:
    name: ratings
  precedence: 2
  route:
  - labels:
      version: v1
  httpFault:
    abort:
      percent: 30
      httpStatus: 500 
