apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: productpage-test-abort
spec:
  destination:
    name: productpage
  precedence: 2
  route:
  - labels:
      version: v1
  httpFault:
    abort:
      percent: 50
      httpStatus: 500 
